export  const GET_FOOD_CATEGORIES_SUCCESS	=	'GET_FOOD_CATEGORIES_SUCCESS';
export  const UPDATE_FOOD_CATEGORY_SUCCESS	=	'UPDATE_FOOD_CATEGORY_SUCCESS';
export  const CREATE_FOOD_CATEGORY_SUCCESS	=	'CREATE_FOOD_CATEGORY_SUCCESS';
export  const DELETE_FOOD_CATEGORY_SUCCESS	=	'DELETE_FOOD_CATEGORY_SUCCESS';