export  const GET_FOOD_TYPES_SUCCESS	=	'GET_FOOD_TYPES_SUCCESS';
export  const UPDATE_FOOD_TYPE_SUCCESS	=	'UPDATE_FOOD_TYPE_SUCCESS';
export  const CREATE_FOOD_TYPE_SUCCESS	=	'CREATE_FOOD_TYPE_SUCCESS';
export  const DELETE_FOOD_TYPE_SUCCESS	=	'DELETE_FOOD_TYPE_SUCCESS';