export  const GET_FOODS_SUCCESS		=	'GET_FOODS_SUCCESS';
export  const UPDATE_FOOD_SUCCESS	=	'UPDATE_FOOD_SUCCESS';
export  const CREATE_FOOD_SUCCESS	=	'CREATE_FOOD_SUCCESS';
export  const DELETE_FOOD_SUCCESS	=	'DELETE_FOOD_SUCCESS';